import{useEffect,useMemo,useRef,useState}from'react';import{api}from'./api';import{cardImages,spreads}from'./data';import type{Interpretation,RevealedCard,Spread,Stage}from'./types';
const back='/assets/card-back-heritage.png';
const cues={shuffle:'/audio/shuffle-soft.wav',cut:'/audio/deck-cut.wav',lift:'/audio/card-lift.wav',place:'/audio/card-place.wav',reveal:'/audio/card-reveal.wav',ready:'/audio/reading-ready.wav'};
function play(name:keyof typeof cues,volume=.45){const a=new Audio(cues[name]);a.volume=volume;a.play().catch(()=>{});return a}
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const initialQuestion='What should I understand about my next chapter?';
const pageContent:Record<string,[string,string[]]>={
 '/learn/how-tarot-works':['How Tarot Works',['Tarot is a structured reflection practice. A question, spread position and card meaning work together to offer a new lens—not a fixed outcome.','Our draw is frozen before selection and the interpretation remains traceable to the cards you actually chose.']],
 '/learn/asking-good-questions':['Asking Good Questions',['Open questions create room for useful reflection. Ask what you can understand, influence or approach differently.','Avoid questions that hand your agency to a prediction.']],
 '/learn/spreads':['Tarot Spreads',['A spread gives every card a specific job. We begin with calibrated three-card structures so the relationship between cards remains readable.']],
 '/cards':['Card Meanings',['Card meanings are starting points rather than verdicts. Upright and reversed meanings, position and context are shown separately.']],
 '/about/interpretation':['Our Interpretation Method',['The draw, source meanings, card relationships, contextual synthesis and action guidance are separate layers. AI may phrase a reading but cannot alter its evidence.']],
 '/about/accuracy':['Accuracy & Uncertainty',['Accuracy here means faithful, specific, internally consistent and useful—not certainty about the future. Confidence measures evidence coverage, not prediction.']],
 '/about/history':['A Short History of Tarot',['Tarot developed from European playing cards before becoming associated with divination. Our visual language draws on printed cards, botanical ornament and the reading table rather than generic astrology.']],
 '/safety':['Safety',['TAROT does not replace medical, legal, financial or mental-health professionals. It never treats a card as a diagnosis or threat.']],
 '/privacy':['Privacy',['Questions are used to provide your reading. Anonymous readings stay in the current browser session unless you choose to save them after signing in.']],
 '/terms':['Terms',['Use TAROT as a reflection aid. You remain responsible for your choices and should seek qualified advice for high-stakes decisions.']]
};

export function App(){
 const[stage,setStage]=useState<Stage>('question'),[question,setQuestion]=useState(initialQuestion),[spread,setSpread]=useState<Spread>(spreads[0]),[sessionId,setSessionId]=useState(''),[selected,setSelected]=useState<number[]>([]),[cards,setCards]=useState<RevealedCard[]>([]),[reading,setReading]=useState<Interpretation|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[route,setRoute]=useState(location.pathname),[loginOpen,setLoginOpen]=useState(false);const activeAudio=useRef<HTMLAudioElement[]>([]);
 useEffect(()=>{const onPop=()=>setRoute(location.pathname);addEventListener('popstate',onPop);const hidden=()=>{if(document.hidden)activeAudio.current.forEach(a=>a.pause())};document.addEventListener('visibilitychange',hidden);return()=>{removeEventListener('popstate',onPop);document.removeEventListener('visibilitychange',hidden)}},[]);
 const go=(path:string)=>{history.pushState({},'',path);setRoute(path);scrollTo(0,0)};
 const sound=(n:keyof typeof cues,v?:number)=>{const a=play(n,v);activeAudio.current.push(a)};
 const begin=()=>{if(question.trim().length<8)return setError('Write a little more so the cards have a clear question.');setError('');setStage('spreads')};
 const shuffle=async()=>{setBusy(true);setError('');try{const s=await api.create(question,spread.id);setSessionId(s.id)}catch(e){setError(e instanceof Error?e.message:'The reading could not start.');setBusy(false);return}sound('shuffle');await wait(matchMedia('(prefers-reduced-motion: reduce)').matches?100:2100);sound('cut');await wait(matchMedia('(prefers-reduced-motion: reduce)').matches?50:700);sound('shuffle',.3);await wait(matchMedia('(prefers-reduced-motion: reduce)').matches?100:1700);sound('cut');await wait(matchMedia('(prefers-reduced-motion: reduce)').matches?50:500);setBusy(false);setStage('select')};
 const pick=async(i:number)=>{if(busy||selected.includes(i)||selected.length>=3)return;const next=[...selected,i];setSelected(next);sound('place');try{await api.select(sessionId,next)}catch(e){setSelected(selected);setError(e instanceof Error?e.message:'Selection failed.')}};
 const reveal=async()=>{if(selected.length!==3)return;setError('');setBusy(true);setStage('reveal');try{const shown=await api.reveal(sessionId);setCards(shown.cards);for(let i=0;i<3;i++){sound('reveal');await wait(matchMedia('(prefers-reduced-motion: reduce)').matches?80:900)}await wait(900);setReading(await api.interpret(sessionId));sound('ready');setStage('result')}catch(e){setError(e instanceof Error?e.message:'The cards could not be revealed.');setStage('select')}finally{setBusy(false)}};
 const restart=()=>{setStage('question');setSelected([]);setCards([]);setReading(null);setSessionId('');setError('')};
 if(route!=='/')return <InfoPage route={route} go={go}/>;
 return <div className={`app stage-${stage}`}><Atmosphere/><Header stage={stage} go={go} onLogin={()=>setLoginOpen(true)}/><main aria-live="polite">{error&&<div role="alert" className="error">{error}</div>}
 {stage==='question'&&<Landing question={question} setQuestion={setQuestion} begin={begin} go={go}/>} 
 {stage==='spreads'&&<SpreadPicker selected={spread} choose={setSpread} continueTo={()=>setStage('shuffle')}/>} 
 {stage==='shuffle'&&<Shuffle question={question} spread={spread} busy={busy} start={shuffle}/>} 
 {stage==='select'&&<Selection spread={spread} selected={selected} pick={pick} remove={i=>{if(busy)return;const next=selected.filter(x=>x!==i);setSelected(next);api.select(sessionId,next).catch(()=>{});sound('lift',.15)}} reveal={reveal}/>} 
 {stage==='reveal'&&<Reveal cards={cards}/>} 
 {stage==='result'&&reading&&<Results question={question} cards={cards} reading={reading} restart={restart} save={()=>api.save(sessionId).catch(e=>setError(e.message))} feedback={value=>api.feedback(sessionId,value).catch(e=>setError(e.message))}/>} </main><Footer go={go}/>{loginOpen&&<LoginModal close={()=>setLoginOpen(false)} setError={setError}/>}</div>
}
function Atmosphere(){return <div className="atmosphere" aria-hidden="true"><i/><b>❦</b><b>❦</b></div>}
function Header({stage,go,onLogin}:{stage:Stage;go:(p:string)=>void;onLogin:()=>void}){const n=['question','spreads','shuffle','select','reveal','result'].indexOf(stage);return <header><button className="brand" onClick={()=>go('/')}>✦ <strong>TAROT</strong></button><nav><button onClick={()=>go('/')}>Readings</button><button onClick={()=>go('/cards')}>Card Meanings</button><button onClick={()=>go('/learn/how-tarot-works')}>Learn</button><button onClick={onLogin}>Sign in</button></nav><div className="progress" aria-label={`Reading step ${n+1} of 6`}>{[0,1,2,3,4,5].map(x=><i key={x} className={x<=n?'on':''}/>)}</div></header>}
function Landing({question,setQuestion,begin,go}:{question:string;setQuestion:(s:string)=>void;begin:()=>void;go:(p:string)=>void}){return <><section className="landing"><div><p className="eyebrow">A QUIET SPACE FOR REFLECTION</p><h1>What would you like<br/><em>clarity on?</em></h1><p className="lede">Ask an open question about what you can understand, influence, or approach differently.</p><label><span>Your question</span><textarea rows={3} maxLength={200} value={question} onChange={e=>setQuestion(e.target.value)}/><small>{question.length} / 200</small></label><button className="primary" onClick={begin}>Begin Your Reading <b>→</b></button><p className="fine">For reflection, not prediction. Your choices remain your own.</p></div><div className="hero" aria-hidden="true"><img src={back}/><img src={back}/><img src={back}/></div></section><section className="home-blocks">{[['How it works','Ask, choose a spread, then select your own cards.','/learn/how-tarot-works'],['Why this reading','Every interpretation stays traceable to the exact cards you draw.','/about/accuracy'],['Explore tarot','Learn the cards, positions and reflective method.','/cards']].map(([h,p,u])=><button key={h} onClick={()=>go(u)}><span>✦</span><h2>{h}</h2><p>{p}</p><b>Explore →</b></button>)}</section></>}
function SpreadPicker({selected,choose,continueTo}:{selected:Spread;choose:(s:Spread)=>void;continueTo:()=>void}){const groups=useMemo(()=>[1,3,6,10].map(n=>[n,spreads.filter(s=>s.cards===n)]as const),[]);return <section className="spread-page"><div className="center"><p className="eyebrow">CHOOSE A SPREAD</p><h1>How deeply would you like <em>to explore?</em></h1><p>Your question remains with you throughout the reading.</p></div>{groups.map(([count,list])=><div className="spread-group" key={count}><h2>{count}-card spreads</h2><div className="spread-grid">{list.map(s=><button key={s.id} disabled={!s.available} className={selected.id===s.id?'chosen':''} onClick={()=>choose(s)}><span>{s.available?(selected.id===s.id?'SELECTED':'AVAILABLE'):'COMING LATER'}</span><div className="backs">{Array.from({length:Math.min(s.cards,6)},(_,i)=><img key={i} src={back}/>)}</div><h3>{s.name}</h3><p>{s.positions.length?s.positions.join(' · '):'A deeper reflective structure'}</p><footer>{s.cards} CARDS <b>ABOUT {s.duration} MINUTES</b></footer></button>)}</div></div>)}<button className="primary sticky-action" onClick={continueTo}>Continue to Shuffling <b>→</b></button></section>}
function Shuffle({question,spread,busy,start}:{question:string;spread:Spread;busy:boolean;start:()=>void}){return <section className="shuffle-page"><p className="eyebrow">{spread.name.toUpperCase()}</p><h1>Hold your question<br/><em>gently in mind.</em></h1><blockquote>“{question}”</blockquote><div className={`deck ${busy?'shuffling':''}`}><img src={back}/><img src={back}/><img src={back}/></div><button disabled={busy} className="primary" onClick={start}>{busy?'Shuffling…':'Shuffle the Deck'} <b>↝</b></button><p className="fine">The order and orientation are fixed before you choose.</p></section>}
function Selection({spread,selected,pick,remove,reveal}:{spread:Spread;selected:number[];pick:(i:number)=>void;remove:(i:number)=>void;reveal:()=>void}){return <section className="selection"><div className="select-head"><div><p className="eyebrow">CHOOSE THREE CARDS</p><h1>Notice what <em>draws you in.</em></h1></div><strong>{selected.length}<span>OF 3 SELECTED</span></strong></div><div className="slots">{spread.positions.map((p,i)=><button key={p} className={selected[i]!==undefined?'filled':''} onClick={()=>selected[i]!==undefined&&remove(selected[i])}>{selected[i]!==undefined?<img src={back}/>:<><b>{['I','II','III'][i]}</b><span>{p}</span></>}</button>)}</div><div className="ribbon" role="listbox" aria-label="Choose from 78 tarot cards">{Array.from({length:78},(_,i)=><button key={i} role="option" aria-selected={selected.includes(i)} aria-label={`Choose card ${i+1}`} className={selected.includes(i)?'picked':''} onFocus={()=>soundQuiet()} onClick={()=>pick(i)}><img src={back}/></button>)}</div><div className="selection-foot"><p>Move slowly. There is no wrong choice.</p><button className="primary" disabled={selected.length!==3} onClick={reveal}>Reveal My Cards <b>→</b></button><p>{selected.length===3?'Your cards are ready':`Choose card ${selected.length+1} of 3`}</p></div></section>}
let lastLift=0;function soundQuiet(){if(Date.now()-lastLift>500){play('lift',.08);lastLift=Date.now()}}
function Reveal({cards}:{cards:RevealedCard[]}){return <section className="reveal"><p className="eyebrow">YOUR THREE-CARD REFLECTION</p><h1>Your cards are <em>ready.</em></h1><div>{cards.length?cards.map((c,i)=><article key={c.cardId} style={{animationDelay:`${i*.8}s`}}><img className={c.orientation==='reversed'?'reversed':''} src={cardImages[Number(c.cardId)]}/><h2>{c.cardName}</h2><p>{c.position} · {c.orientation}</p></article>):[0,1,2].map(i=><article key={i}><img src={back}/></article>)}</div><p>Take a breath and meet them one at a time.</p></section>}
function Results({question,cards,reading,restart,save,feedback}:{question:string;cards:RevealedCard[];reading:Interpretation;restart:()=>void;save:()=>void;feedback:(v:boolean)=>void}){return <section className="results"><div className="result-head"><div><p className="eyebrow">YOUR READING</p><h1>A quieter view of<br/><em>what comes next.</em></h1><blockquote>“{question}”</blockquote></div><button onClick={restart}>New reading</button></div><div className="overview">{cards.map(c=><article key={`${c.positionId}-${c.cardId}`}><span>{c.position}</span><img className={c.orientation==='reversed'?'reversed':''} src={cardImages[Number(c.cardId)]}/><h2>{c.cardName}</h2><p>{c.orientation}</p></article>)}</div><div className="thread"><p className="eyebrow">THE THREAD BETWEEN THEM</p><h2>{reading.synthesis}</h2>{reading.relations.map(x=><p key={x}>{x}</p>)}</div><div className="long-reading">{reading.sections.map((s,i)=><article key={s.cardId} className={i%2?'alternate':''}><div className="meaning"><span>{s.position}</span><h2>{s.cardName} <em>{s.orientation}</em></h2><h3>Base meaning</h3><p>{s.baseMeaning}</p><h3>In your context</h3><p>{s.contextualMeaning}</p><h3>In relation</h3><p>{s.relation}</p><blockquote>{s.reflectionQuestion}</blockquote></div><img className={s.orientation==='reversed'?'reversed':''} src={cardImages[Number(s.cardId)]}/></article>)}</div><div className="closing"><div><span>Your next step</span><h2>{reading.nextStep}</h2></div><div><span>Interpretive confidence</span><h2>{reading.confidence.level}</h2><meter min="0" max="1" value={reading.confidence.score}/><p>{reading.confidence.meaning} {reading.confidence.uncertainty}</p></div><p>{reading.safety}</p><div className="result-actions"><button onClick={save}>Save reading</button><span>Was this useful?</span><button onClick={()=>feedback(true)}>Yes</button><button onClick={()=>feedback(false)}>Not yet</button></div></div></section>}
function LoginModal({close,setError}:{close:()=>void;setError:(s:string)=>void}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const id=import.meta.env.VITE_GOOGLE_CLIENT_ID;if(!id||!window.google)return;window.google.accounts.id.initialize({client_id:id,callback:async({credential}:{credential:string})=>{try{await api.google(credential);close()}catch(e){setError(e instanceof Error?e.message:'Sign in failed.')}}});window.google.accounts.id.renderButton(ref.current!,{theme:'outline',size:'large',width:280})},[close,setError]);return <div className="modal" role="dialog" aria-modal="true"><div><button className="close" onClick={close}>×</button><p className="eyebrow">SAVE YOUR REFLECTIONS</p><h2>Sign in to TAROT</h2><p>Reading never requires an account. Sign in only when you want to save and revisit it.</p><div ref={ref}>{!import.meta.env.VITE_GOOGLE_CLIENT_ID&&<p className="fine">Google sign-in will appear when the production client ID is configured.</p>}</div><button onClick={close}>Continue without account</button></div></div>}
function InfoPage({route,go}:{route:string;go:(p:string)=>void}){const content=pageContent[route]||['Page not found',['The page you requested is not available.']];return <div className="app"><Atmosphere/><Header stage="question" go={go} onLogin={()=>{}}/><main><article className="info"><p className="eyebrow">TAROT · LEARN</p><h1>{content[0]}</h1>{content[1].map(p=><p key={p}>{p}</p>)}<button className="primary" onClick={()=>go('/')}>Begin a reading <b>→</b></button></article></main><Footer go={go}/></div>}
function Footer({go}:{go:(p:string)=>void}){return <footer><span>© TAROT</span><nav><button onClick={()=>go('/about/interpretation')}>Method</button><button onClick={()=>go('/safety')}>Safety</button><button onClick={()=>go('/privacy')}>Privacy</button><button onClick={()=>go('/terms')}>Terms</button></nav><em>Reflection over certainty</em></footer>}
declare global{interface Window{google?:{accounts:{id:{initialize:(x:unknown)=>void;renderButton:(el:HTMLElement,x:unknown)=>void}}}}}
