import type { Spread } from "./types";
export const spreads: Spread[] = [
  {
    id: "general-reflection",
    name: "General Reflection",
    cards: 3,
    available: true,
    duration: 3,
    positions: ["Background", "Core", "Guidance"],
  },
  {
    id: "relationship-reflection",
    name: "Relationship Reflection",
    cards: 3,
    available: true,
    duration: 3,
    positions: ["Your Perspective", "Shared Dynamic", "Healthy Next Step"],
  },
  {
    id: "work-direction",
    name: "Work & Direction",
    cards: 3,
    available: true,
    duration: 3,
    positions: ["Current Reality", "Friction", "Practical Next Step"],
  },
  {
    id: "decision-clarity",
    name: "Decision Clarity",
    cards: 3,
    available: true,
    duration: 3,
    positions: ["What Matters", "What Complicates", "Next Step"],
  },
  {
    id: "daily-reflection",
    name: "Daily Reflection",
    cards: 1,
    available: true,
    duration: 1,
    positions: ["Today's Focus"],
    layout: "single",
  },
  {
    id: "single-focus",
    name: "One-Card Reflection",
    cards: 1,
    available: true,
    duration: 1,
    positions: ["Focus"],
    layout: "single",
  },
  {
    id: "past-present-next",
    name: "Past, Present & Next",
    cards: 3,
    available: true,
    duration: 3,
    positions: ["Past Influence", "Present Reality", "Next Development"],
    layout: "row",
  },
  {
    id: "mind-body-spirit",
    name: "Mind, Body & Spirit",
    cards: 3,
    available: true,
    duration: 3,
    positions: ["Mind", "Body & Reality", "Spirit"],
    layout: "row",
  },
  {
    id: "creative-block",
    name: "Creative Block",
    cards: 3,
    available: true,
    duration: 3,
    positions: ["Spark", "Block", "Experiment"],
    layout: "row",
  },
  {
    id: "relationship-check-in",
    name: "Relationship Check-in",
    cards: 6,
    available: true,
    duration: 7,
    positions: [
      "Your Perspective",
      "Observable Dynamic",
      "Unspoken Need",
      "Boundary to Honor",
      "Support Available",
      "Healthy Next Step",
    ],
    layout: "six-grid",
  },
  {
    id: "whole-self",
    name: "Six-Card Reflection",
    cards: 6,
    available: true,
    duration: 7,
    positions: [
      "Current Reality",
      "Underlying Influence",
      "Main Friction",
      "Available Strength",
      "Helpful Adjustment",
      "Practical Next Step",
    ],
    layout: "six-grid",
  },
  {
    id: "seasonal-review",
    name: "Seasonal Review",
    cards: 6,
    available: true,
    duration: 7,
    positions: [
      "What Is Ending",
      "What Remains",
      "Lesson to Carry",
      "Resource Available",
      "Intention to Set",
      "Practical Next Step",
    ],
    layout: "six-grid",
  },
  {
    id: "celtic-cross-classic",
    name: "Celtic Cross",
    cards: 10,
    available: true,
    duration: 12,
    positions: [
      "Present Situation",
      "Challenge",
      "Foundation",
      "Recent Past",
      "Possibility",
      "Near Development",
      "Your Approach",
      "External Influences",
      "Hopes & Fears",
      "Direction",
    ],
    layout: "celtic-cross",
  },
  {
    id: "celtic-cross-reflective",
    name: "Celtic Cross (Reflective)",
    cards: 10,
    available: true,
    duration: 12,
    positions: [
      "Current Awareness",
      "Central Tension",
      "Underlying Pattern",
      "What Is Receding",
      "Emerging Possibility",
      "Near-Term Practice",
      "Your Stance",
      "Surrounding Context",
      "Hope & Concern",
      "Reflective Direction",
    ],
    layout: "celtic-cross",
  },
];
const major = [
  "00-TheFool",
  "01-TheMagician",
  "02-TheHighPriestess",
  "03-TheEmpress",
  "04-TheEmperor",
  "05-TheHierophant",
  "06-TheLovers",
  "07-TheChariot",
  "08-Strength",
  "09-TheHermit",
  "10-WheelOfFortune",
  "11-Justice",
  "12-TheHangedMan",
  "13-Death",
  "14-Temperance",
  "15-TheDevil",
  "16-TheTower",
  "17-TheStar",
  "18-TheMoon",
  "19-TheSun",
  "20-Judgement",
  "21-TheWorld",
];
const suits = ["Wands", "Cups", "Swords", "Pentacles"];
export const cardImages = [
  ...major,
  ...suits.flatMap((s) =>
    Array.from(
      { length: 14 },
      (_, i) => `${s}${String(i + 1).padStart(2, "0")}`,
    ),
  ),
].map((x) => `/assets/cards/${x}.png`);
